preprocess: V5
output: "setting_5.csv"
datadir: "data"
outdir: "submissions"
n_estimators: [300]
max_depth: [25, 30]
min_samples_leaf: [5, 7, 9]
learning_rate: 0.05
iterations: 5000
l2_leaf_reg: 50.0
depth: 5
langevin: false
logging_level: 200
